


# hostname: localhost
hostname: ${WEB_HOSTNAME:-fe-pipeline.localhost}

fe-port: 8000
fe-path: /

backend-port: 3000
ingress-backend-port: 3000

# proxy-backend-host: 127.0.0.1
# proxy-backend-port: 80

auth:
  oauthConfig:
    github:
      client_secret: 1876ba4ec1f92abc2fb3285cefa2c75d9eb3f5c9
      client_id: a18b1ae435db47650112
