


# hostname: localhost
hostname: ${WEB_HOSTNAME:-fe-pipeline.localhost:8000}

fe-port: 8000
fe-path: /

backend-port: 3000
ingress-backend-port: 3000

existingClaimForWs: fe-pipeline-pvc2

# proxy-backend-host: 127.0.0.1
# proxy-backend-port: 80

# auth:
#   oauthConfig:
#     github:
#       client_secret: 1876ba4ec1f92abc2fb3285cefa2c75d9eb3f5c9
#       client_id: a18b1ae435db47650112

authProviders:
  - id: "GitLab"
    host: "code.choerodon.com.cn"
    protocol: "https"
    type: "GitLab"
    oauth:
      args:
        response_type: code
        scope: 'read_user api'
      clientId: "92fdff9ebedb28166c425b902045285bb7d45c138fc8ed8b902f6e5d0d1070ca"
      clientSecret: "623c4aaa71e60d86b6e04e64983298d7cdcb5fbabeee51d8c729a8c0d59f4456"
      callBackUrl: "/oauth/authorize"
      settingsUrl: "https://code.choerodon.com.cn/profile/applications"

  - id: "Github"
    host: "github.com"
    protocol: "https"
    type: "GitHub"
    oauth:
      args:
        scope: user:email
      clientId: "ea1ed85b812f07ede99a"
      clientSecret: "c91adc1052627475aee4bd7b547f4a8a5e724210"
      callBackUrl: "/login/oauth/authorize"
      settingsUrl: "https://github.com/settings/connections/applications/4f5afda4c1420c3e0dd4"

  - id: "Choerodon"
    host: "api.choerodon.com.cn"
    protocol: "https"
    type: "Choerodon"
    oauth:
      args:
        response_type: token
      clientId: "localhost"
      # clientSecret: "49ffb90f07a2dfa40623c37c06f77a90a3b21be7"
      callBackUrl: "/oauth/oauth/authorize"
      # settingsUrl: "https://github.com/settings/connections/applications/4f5afda4c1420c3e0dd4"

  - id: "open-hand"
    host: "gateway.open.hand-china.com"
    protocol: "https"
    type: "open-hand"
    oauth:
      args:
        response_type: token
      clientId: "hsop-app"
      # clientSecret: "49ffb90f07a2dfa40623c37c06f77a90a3b21be7"
      callBackUrl: "/oauth/oauth/authorize"
      # settingsUrl: "https://github.com/settings/connections/applications/4f5afda4c1420c3e0dd4"
