
# homeDir: /tmp/fe-pipeline
# db:
#   type: 'mysql'
#   host: 'localhost'
#   port: 3306
#   username: 'root'
#   password: 'root'
#   database: 'test'

auth:
  oauthConfig:
    github:
      client_secret: 2e6c3b196c09f0f5c0e47f02f1175586b16b742b
      client_id: f236349a490be375714e
      
HELLO_MESSAGE: 'Hello there, world!'

# hostname: localhost
hostname: ${WEB_HOSTNAME:-fe-pipeline.localhost}
fe-port: 80
fe-path: /fed/
