
# homeDir: /tmp/fe-pipeline
# db:
#   type: 'mysql'
#   host: 'localhost'
#   port: 3306
#   username: 'root'
#   password: 'root'
#   database: 'test'

HELLO_MESSAGE: 'Hello there, world!'

# hostname: localhost
hostname: ${WEB_HOSTNAME:-fe-pipeline.localhost}
fe-port: 80
fe-path: /
