# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

# requirements.yaml
dependencies:
- name: minio
  version: 8.0.7
  repository: https://helm.min.io/
  condition: minio.enabled
- name: redis
  version: 14.3.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled 
