apiVersion: v1
kind: Namespace
metadata:
  name: fe-pipeline

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-fe-pipeline-deployment
  labels:
    app: dev-fe-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-fe-pipeline
  template:
    metadata:
      labels:
        app: dev-fe-pipeline
    spec:
      volumes:
        - name: ws-volume
          hostPath:
            path: "${WS_PWD}"
            type: Directory
          # emptyDir: {}
      containers:
      - name: 'main'
        image: 'registry.cn-hangzhou.aliyuncs.com/jajabjbj/theia-app:dev-hand'
        securityContext:
          privileged: true
        ports:
        - name: backend
          containerPort: 3000
          protocol: TCP
          # hostPort: 3000
        - name: fed
          containerPort: 8000
          protocol: TCP
        - name: debug
          containerPort: 9229
          protocol: TCP
        volumeMounts:
        - name: ws-volume
          mountPath: "${WS_PWD}"
        # env:
        # - name: 'FED_BASE_PATH'
        #   value: '/app/'
        # - name: 'FED_PUBLIC_PATH'
        #   value: '/app/'
        # - name: 'WDS_SOCKET_HOST'
        #   value: 'localhost'
        # - name: 'WDS_SOCKET_PORT'
        #   value: '80'
        # - name: 'WDS_SOCKET_PATH'
        #   value: '/app/'
        command: ["/bin/bash", "-c"]
        args: ["while true;do echo 'Press CTRL+C to Exit' && sleep 10000; done"]
        # args: ["python3 -m http.server 8000"]/
        workingDir: "${WS_PWD}"

---

apiVersion: v1
kind: Service
metadata:
  name: dev-fe-pipeline
spec:
  clusterIP: None
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: fe-http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: debug
    port: 9229
    protocol: TCP
    targetPort: 9229
  selector:
    app: dev-fe-pipeline
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/client-max-body-size: 500m
    nginx.org/websocket-services: dev-fe-pipeline
  name: fe-pipeline-ing
spec:
  rules:
  - host: fe-pipeline.localhost
    http:
      paths:
      - backend:
          serviceName: dev-fe-pipeline
          servicePort: http
        path: /
        pathType: ImplementationSpecific
  - host: '*.ws.fe-pipeline.localhost'
    http:
      paths:
      - backend:
          serviceName: dev-fe-pipeline
          servicePort: http
        path: /
        pathType: ImplementationSpecific

