{{- $fullName := include "fe-pipeline.fullname" . -}}

# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-config
  labels:
    {{- include "fe-pipeline.labels" . | nindent 4 }}
data:
  config.production.yml: |-
    HELLO_MESSAGE: 'Hello there, world!, production'
    minio:
      endpoint: {{ default ( printf "http://%s.%s.svc.cluster.local:9000"  (index .Values "minio" "fullnameOverride") ( .Release.Namespace )) .Values.minio.endpoint }}
      accessKey: minioadmin
      secretKey: minioadmin
    redis:
      endpoint_ip: {{ default ( printf "%s-master.%s.svc.cluster.local"  (index .Values "redis" "fullnameOverride") ( .Release.Namespace )) .Values.redis.endpoint_ip }}
      endpoint_port: {{ default "6379" .Values.redis.endpoint_port }}
    existingClaimForWs: {{ .Values.persistence.existingClaim }}
    hostname: {{.Values.hostname}}
    fe-port: 80
    fe-path: /fed/
    authProviders:
{{ toYaml .Values.authProviders | indent 6 }}
