{{- $fullName := include "fe-pipeline.fullname" . -}} 

# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-proxy-config
  labels:
    {{- include "fe-pipeline.labels" . | nindent 4 }}
data:
  default.conf: |-
    # nginx.vh.default.conf  --  docker-openresty
    #
    # This file is installed to:
    #   `/etc/nginx/conf.d/default.conf`
    #
    # It tracks the `server` section of the upstream OpenResty's `nginx.conf`.
    #
    # This config (and any other configs in `etc/nginx/conf.d/`) is loaded by
    # default by the `include` directive in `/usr/local/openresty/nginx/conf/nginx.conf`.
    #
    # See https://github.com/openresty/docker-openresty/blob/master/README.md#nginx-config-files
    #

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }


    server {
        listen       80;
        server_name  {{ .Values.hostname }};


        location / {
            proxy_pass   http://{{ $fullName }}-manager:3000;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

    }

        
    server {
        listen       80;
        server_name  ~^(.*)\.ms\.(.*)$;

        set $fe_pipeline_project_id $1;
        set $fe_pipeline_manager_host $2;

        location / {
            root /app/fe-pipeline-home/data/ms-public/$fe_pipeline_project_id;
            index index.html index.htm;
        }

        error_page  404 =404 @fallback;

        location @fallback {
            root /app/fe-pipeline-home/data/ms-public/$fe_pipeline_project_id;
            rewrite ^(.*)$ /404.html break;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/openresty/nginx/html;
        }

    }
