{{- $fullName := include "fe-pipeline.fullname" . -}}

# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}-{{ .Release.Namespace }}-ns-fe-pipeline-binding
  labels:
    {{- include "fe-pipeline.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "fe-pipeline.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $fullName }}-{{ .Release.Namespace }}-ns-fe-pipeline
  apiGroup: rbac.authorization.k8s.io