{{- $fullName := include "fe-pipeline.fullname" . -}}

# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}-rolebinding
  labels:
    {{- include "fe-pipeline.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-pods-reader
subjects:
- kind: ServiceAccount
  name: {{ include "fe-pipeline.serviceAccountName" . }}
