{{- $fullName := include "fe-pipeline.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-proxy
  labels:
    {{- include "fe-pipeline.labels" . | nindent 4 }}
    fe-pipeline: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      fe-pipeline: proxy
      {{- include "fe-pipeline.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fe-pipeline.selectorLabels" . | nindent 8 }}
        fe-pipeline: proxy
    spec:
      volumes:
      - name: config
        configMap:
          name: {{ $fullName }}-proxy-config
      - name: fe-pipeline-ms-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      containers:
      - name: 'proxy'
        image: 'registry.cn-hangzhou.aliyuncs.com/jajabjbj/openresty:alpine'
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: config
            subPath: 'default.conf'
          - mountPath: /app/fe-pipeline-home/data
            name: fe-pipeline-ms-data
            {{- if not (empty .Values.persistence.subPath) }}
            subPath: {{ .Values.persistence.subPath }}
            {{- end }}
        # securityContext:
        #   privileged: true
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
