{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
{{ include "fe-pipeline.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if not (empty .Values.service.externalIPs) }}
  externalIPs: 
{{ toYaml .Values.service.externalIPs | indent 2 }}
{{- end }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    fe-pipeline: proxy
{{ include "fe-pipeline.selectorLabels" . | indent 4 }}
{{- end }}
