{{- if .Values.service.enabled }}

{{- $fullName := include "fe-pipeline.fullname" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-manager
  labels:
{{ include "fe-pipeline.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if not (empty .Values.service.externalIPs) }}
  externalIPs: 
{{ toYaml .Values.service.externalIPs | indent 2 }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    fe-pipeline: ws-manager
{{ include "fe-pipeline.selectorLabels" . | indent 4 }}
{{- end }}
